{ pkgs, modulesPath, ... }: 

{
  imports = [
    # Autogenerated configuration specific to the iso, and not included in repo
    (modulesPath + "/virtualisation/proxmox-lxc.nix")
    
    # Add host configuration
    ./hosts/minimal/minimal.nix
  ];
	
  environment.systemPackages = with pkgs; [
		
  ];

  system.stateVersion = "24.05";
}
